<?php
if(isset($view->errors))
{
    foreach($view->errors as $error)
    {
        echo"<div class='alert alert-danger border border-danger' role='alert'>"."<i class='bi bi-exclamation-triangle'></i>"."  $error  "."</div>";
    }
}


?>

<div class="container">
    <div class="text-center">
        <h1>ParcelBuddy</h1>
    </div>


    <div class="row justify-content-center mt-5">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title text-center">Log into your account</h5>
            <form action="<?php htmlentities($_SERVER["PHP_SELF"]); ?>" method="post">
                <div class="col-md-12 mb-2">
                    <label class="mb-2" for="username">Username</label>
                    <input type="text" class="form-control" name="username" id="username" required>
                </div>
                <div class="col-md-12 ">
                    <label class="mb-2" for="password">Password</label>
                    <input type="password" class="form-control" name="password" id="password" required>
                </div>
                <div class="col-md-12 text-center mt-3" >
                    <input type="submit" class="btn btn-primary btn-block" name="login" value="Login">
                    <a class="btn btn-dark mt-5" id="markScheme" href="../markScheme.docx">Download mark scheme</a>
                </div>
            </form>
            </div>
        </div>
    </div>

</div>



