<?php ?>
<nav class="navbar navbar-expand-md navbar-light">
    <div class="container-xxl">
      <!-- navbar brand / title -->
      <a class="navbar-brand">
        <span class="text-secondary fw-bold">
ParcelBuddy
</span>
      </a>
      <!-- toggle button for mobile nav -->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#manager-nav" aria-controls="manager-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- navbar links -->
      <div class="collapse navbar-collapse justify-content-end align-center" id="manager-nav">
        <ul class="navbar-nav">
          <li class="nav-item">
              <form action="<?php echo htmlentities($_SERVER["PHP_SELF"]); ?>" method="post">
                <button type="submit" class="btn btn-secondary m-2" name="viewUsers" value="viewUsers">View Users</button>
              </form>
          </li>
          <li class="nav-item">
              <form action="<?php echo htmlentities($_SERVER["PHP_SELF"]); ?>" method="post">
                  <button type="submit" class="btn btn-secondary m-2" name="viewDeliveries" value="viewDeliveries">View Deliveries</button>
              </form>
          </li>
            <li class="nav-item">
                <form action="<?php echo htmlentities($_SERVER["PHP_SELF"]); ?>" method="post">
                    <button type="submit" class="btn btn-danger m-2" name="logout" value="logout">Logout</button>
                </form>
            </li>
        </ul>
      </div>
    </div>
  </nav>